/* GENERATED FILE — do not edit.
   Source: data/tools.mjs via scripts/generate-catalogue-runtime.mjs
   (npm run generate:catalogue-runtime). Delivers the tool catalogue's library
   sources, per-tool dependencies and breadcrumbs to the runtime app. */
window.WCF_CATALOGUE = {
  "libraries": {
    "jspdf": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
    },
    "pdfjs": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.4.120/pdf.min.js"
    },
    "pdflib": {
      "src": "https://cdn.jsdelivr.net/npm/pdf-lib-with-encrypt@1.2.1/dist/pdf-lib.min.js"
    },
    "papa": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js"
    },
    "xlsx": {
      "src": "https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js"
    },
    "jszip": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"
    },
    "mammoth": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.6.0/mammoth.browser.min.js"
    },
    "html2pdf": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"
    },
    "docx": {
      "src": "https://cdn.jsdelivr.net/npm/docx@8.5.0/build/index.umd.js"
    },
    "jspdfautotable": {
      "src": "https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js"
    },
    "cryptojs": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"
    },
    "qrious": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js"
    },
    "exif": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.3.0/exif.min.js"
    },
    "heic2any": {
      "src": "https://cdn.jsdelivr.net/npm/heic2any@0.0.4/dist/heic2any.min.js"
    },
    "marked": {
      "src": "https://cdn.jsdelivr.net/npm/marked/marked.min.js"
    },
    "diff": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/diff_match_patch/20121119/diff_match_patch.js"
    },
    "jsyaml": {
      "src": "https://cdn.jsdelivr.net/npm/js-yaml@4.1.0/dist/js-yaml.min.js"
    },
    "sqlformatter": {
      "src": "https://cdn.jsdelivr.net/npm/sql-formatter@15.8.2/dist/sql-formatter.min.js"
    },
    "terser": {
      "src": "https://cdn.jsdelivr.net/npm/terser@5.49.0/dist/bundle.min.js"
    },
    "csso": {
      "src": "https://cdn.jsdelivr.net/npm/csso@5.0.5/dist/csso.js"
    },
    "jsbeautifyjs": {
      "src": "https://cdn.jsdelivr.net/npm/js-beautify@2.0.3/js/lib/beautify.js"
    },
    "jsbeautifycss": {
      "src": "https://cdn.jsdelivr.net/npm/js-beautify@2.0.3/js/lib/beautify-css.js"
    },
    "jsbeautifyhtml": {
      "src": "https://cdn.jsdelivr.net/npm/js-beautify@2.0.3/js/lib/beautify-html.js"
    },
    "cropper": {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js",
      "css": "https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.css"
    }
  },
  "dependencies": {
    "pdf-to-word": [
      "pdfjs"
    ],
    "office-pdf": [
      "html2pdf",
      "mammoth",
      "xlsx"
    ],
    "merge-pdf": [
      "pdflib"
    ],
    "images-pdf": [
      "jspdf"
    ],
    "compress-pdf": [
      "pdfjs",
      "jspdf"
    ],
    "heic-to-jpg": [
      "heic2any",
      "jszip"
    ],
    "split-pdf": [
      "pdflib",
      "jszip"
    ],
    "pdf-images": [
      "pdfjs",
      "jszip"
    ],
    "pdf-jpg": [
      "pdfjs",
      "jszip"
    ],
    "qr-generator": [
      "qrious"
    ],
    "sign-pdf": [
      "pdflib"
    ],
    "image-cropper": [
      "cropper"
    ],
    "extract-pages": [
      "pdflib"
    ],
    "remove-pages": [
      "pdfjs",
      "pdflib"
    ],
    "bulk-resize": [
      "jszip"
    ],
    "excel-to-csv": [
      "xlsx"
    ],
    "webp-convert": [
      "jszip"
    ],
    "organize-pdf": [
      "pdfjs",
      "pdflib"
    ],
    "watermark-pdf": [
      "pdflib"
    ],
    "page-numbers": [
      "pdflib"
    ],
    "rotate-pdf": [
      "pdfjs",
      "pdflib"
    ],
    "encrypt-pdf": [
      "pdflib"
    ],
    "json-convert": [
      "xlsx"
    ],
    "csv-convert": [
      "papa",
      "xlsx"
    ],
    "favicon-generator": [
      "jszip"
    ],
    "diff-checker": [
      "diff"
    ],
    "markdown-preview": [
      "marked"
    ],
    "hash-generator": [
      "cryptojs"
    ],
    "exif-utility": [
      "exif"
    ],
    "decrypt-pdf": [
      "pdflib",
      "pdfjs",
      "jspdf"
    ],
    "json-yaml": [
      "jsyaml"
    ],
    "sql-formatter": [
      "sqlformatter"
    ]
  },
  "breadcrumbs": {
    "image-to-base64": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Image to Base64</span></li>\n  </ol>\n</nav>",
    "base64-to-image": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Base64 to Image</span></li>\n  </ol>\n</nav>",
    "svg-to-image": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">SVG to PNG / JPG</span></li>\n  </ol>\n</nav>",
    "pdf-to-word": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">PDF to Word / TXT</span></li>\n  </ol>\n</nav>",
    "office-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/convert-office\">Convert &amp; Office Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Word / Excel to PDF</span></li>\n  </ol>\n</nav>",
    "merge-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Merge PDF</span></li>\n  </ol>\n</nav>",
    "images-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Images to PDF</span></li>\n  </ol>\n</nav>",
    "compress-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Compress PDF</span></li>\n  </ol>\n</nav>",
    "heic-to-jpg": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">HEIC to JPG / PNG</span></li>\n  </ol>\n</nav>",
    "split-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Split PDF</span></li>\n  </ol>\n</nav>",
    "pdf-images": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">PDF to PNG</span></li>\n  </ol>\n</nav>",
    "pdf-jpg": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">PDF to JPG</span></li>\n  </ol>\n</nav>",
    "qr-generator": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">QR Code Generator</span></li>\n  </ol>\n</nav>",
    "sign-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Sign PDF</span></li>\n  </ol>\n</nav>",
    "image-cropper": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Crop Image</span></li>\n  </ol>\n</nav>",
    "extract-pages": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Extract Pages</span></li>\n  </ol>\n</nav>",
    "remove-pages": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Remove Pages</span></li>\n  </ol>\n</nav>",
    "bulk-resize": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Bulk Image Resizer</span></li>\n  </ol>\n</nav>",
    "excel-to-csv": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/convert-office\">Convert &amp; Office Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Excel to CSV / JSON</span></li>\n  </ol>\n</nav>",
    "word-counter": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Word &amp; Character Counter</span></li>\n  </ol>\n</nav>",
    "image-scaler": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Scale Image</span></li>\n  </ol>\n</nav>",
    "webp-convert": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Image to WebP</span></li>\n  </ol>\n</nav>",
    "organize-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Organize PDF</span></li>\n  </ol>\n</nav>",
    "watermark-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Watermark PDF</span></li>\n  </ol>\n</nav>",
    "page-numbers": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Add Page Numbers</span></li>\n  </ol>\n</nav>",
    "rotate-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Rotate PDF</span></li>\n  </ol>\n</nav>",
    "encrypt-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Protect PDF</span></li>\n  </ol>\n</nav>",
    "json-convert": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/convert-office\">Convert &amp; Office Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">JSON to CSV / Excel</span></li>\n  </ol>\n</nav>",
    "csv-convert": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/convert-office\">Convert &amp; Office Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">CSV to Excel or JSON</span></li>\n  </ol>\n</nav>",
    "json-formatter": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">JSON Formatter / Validator</span></li>\n  </ol>\n</nav>",
    "color-palette": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Image Color Picker &amp; Eyedropper</span></li>\n  </ol>\n</nav>",
    "favicon-generator": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Favicon Generator</span></li>\n  </ol>\n</nav>",
    "diff-checker": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Code Diff Checker</span></li>\n  </ol>\n</nav>",
    "url-base64": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">URL / Base64 Converter</span></li>\n  </ol>\n</nav>",
    "markdown-preview": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Markdown Live Preview</span></li>\n  </ol>\n</nav>",
    "regex-tester": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Regex Tester</span></li>\n  </ol>\n</nav>",
    "jwt-decoder": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">JWT Decoder</span></li>\n  </ol>\n</nav>",
    "uuid-generator": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">UUID Generator</span></li>\n  </ol>\n</nav>",
    "hash-generator": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Hash Generator</span></li>\n  </ol>\n</nav>",
    "exif-utility": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/image-tools\">Image Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">EXIF Viewer / Remover</span></li>\n  </ol>\n</nav>",
    "unix-converter": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Unix Time Converter</span></li>\n  </ol>\n</nav>",
    "decrypt-pdf": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/pdf-tools\">PDF Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Unlock PDF</span></li>\n  </ol>\n</nav>",
    "json-yaml": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/convert-office\">Convert &amp; Office Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">JSON to YAML Converter</span></li>\n  </ol>\n</nav>",
    "sql-formatter": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">SQL Formatter</span></li>\n  </ol>\n</nav>",
    "code-minifier": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Code Minifier &amp; Beautifier</span></li>\n  </ol>\n</nav>",
    "password-generator": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Password &amp; Secret Generator</span></li>\n  </ol>\n</nav>",
    "case-converter": "<nav aria-label=\"Breadcrumb\" class=\"mb-6\">\n  <ol class=\"flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-slate-500 dark:text-slate-400\">\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/\">Home</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><a class=\"rounded hover:text-[#1a73e8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1a73e8]\" href=\"/category/developer-tools\">Text &amp; Developer Tools</a></li>\n  <li aria-hidden=\"true\" class=\"select-none text-slate-300 dark:text-slate-600\">/</li>\n  <li class=\"min-w-0 max-w-[60vw] truncate\"><span aria-current=\"page\" class=\"font-medium text-slate-700 dark:text-slate-300\">Case Converter</span></li>\n  </ol>\n</nav>"
  }
};
