const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '../index.html');
let html = fs.readFileSync(file, 'utf8');

// Fix json-yaml
html = html.replace(
  '<div class="grid grid-cols-1 md:grid-cols-2 gap-4 h-[400px]">\n            <div class="flex flex-col h-full bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl overflow-hidden shadow-sm">\n              <div class="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-slate-700/60 bg-white dark:bg-slate-800">\n                <span class="text-xs font-bold text-slate-500 uppercase">Input</span>\n                <button type="button" id="jySwapBtn" class="p-1 rounded bg-slate-100 hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-600 transition" aria-label="Swap directions" title="Swap Input/Output"><svg class="w-4 h-4 text-slate-600 dark:text-slate-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 7h12M16 3l4 4-4 4M16 17H4M8 21l-4-4 4-4"/></svg></button>\n              </div>\n              <textarea id="jyInput" class="flex-grow w-full p-4 bg-transparent outline-none resize-none text-sm text-slate-800 dark:text-slate-200 font-mono" placeholder="Paste JSON or YAML here..." spellcheck="false"></textarea>\n            </div>\n            <div class="flex flex-col h-full bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl overflow-hidden shadow-sm">\n              <div class="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-slate-700/60 bg-white dark:bg-slate-800">\n                <span class="text-xs font-bold text-slate-500 uppercase">Output</span>\n                <div class="flex gap-2">\n                  <button type="button" id="jyCopyBtn" class="px-2 py-1 text-xs font-bold bg-blue-50 text-blue-600 rounded hover:bg-blue-100 transition">Copy</button>\n                  <button type="button" id="jyDownloadBtn" class="px-2 py-1 text-xs font-bold bg-teal-50 text-teal-600 border border-teal-200 dark:border-teal-900/50 rounded hover:bg-teal-100 transition">Download</button>\n                  <button type="button" id="jyClearBtn" class="px-2 py-1 text-xs font-bold bg-rose-50 text-rose-600 rounded hover:bg-rose-100 transition">Clear</button>\n                </div>\n              </div>\n              <textarea id="jyOutput" class="flex-grow w-full p-4 bg-transparent outline-none resize-none text-sm text-slate-800 dark:text-slate-200 font-mono" readonly placeholder="Output will appear here..."></textarea>\n            </div>\n          </div>',
  '<div class="grid grid-cols-1 md:grid-cols-2 gap-4 min-h-[400px]">\n            <div class="flex flex-col bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl overflow-hidden shadow-sm">\n              <div class="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-slate-700/60 bg-white dark:bg-slate-800">\n                <span class="text-xs font-bold text-slate-500 uppercase">Input</span>\n                <button type="button" id="jySwapBtn" class="p-1 rounded bg-slate-100 hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-600 transition" aria-label="Swap directions" title="Swap Input/Output"><svg class="w-4 h-4 text-slate-600 dark:text-slate-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 7h12M16 3l4 4-4 4M16 17H4M8 21l-4-4 4-4"/></svg></button>\n              </div>\n              <textarea id="jyInput" class="w-full p-4 bg-transparent outline-none resize-y text-sm text-slate-800 dark:text-slate-200 font-mono" style="min-height: 400px; height: auto;" oninput="this.style.height=\'auto\'; this.style.height = this.scrollHeight + \'px\'; const out = document.getElementById(\'jyOutput\'); if(out) { out.style.height=\'auto\'; out.style.height = out.scrollHeight + \'px\'; }" placeholder="Paste JSON or YAML here..." spellcheck="false"></textarea>\n            </div>\n            <div class="flex flex-col bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl overflow-hidden shadow-sm">\n              <div class="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-slate-700/60 bg-white dark:bg-slate-800">\n                <span class="text-xs font-bold text-slate-500 uppercase">Output</span>\n                <div class="flex gap-2">\n                  <button type="button" id="jyCopyBtn" class="px-2 py-1 text-xs font-bold bg-blue-50 text-blue-600 rounded hover:bg-blue-100 transition">Copy</button>\n                  <button type="button" id="jyDownloadBtn" class="px-2 py-1 text-xs font-bold bg-teal-50 text-teal-600 border border-teal-200 dark:border-teal-900/50 rounded hover:bg-teal-100 transition">Download</button>\n                  <button type="button" id="jyClearBtn" class="px-2 py-1 text-xs font-bold bg-rose-50 text-rose-600 rounded hover:bg-rose-100 transition">Clear</button>\n                </div>\n              </div>\n              <textarea id="jyOutput" class="w-full p-4 bg-transparent outline-none resize-y text-sm text-slate-800 dark:text-slate-200 font-mono" style="min-height: 400px; height: auto;" readonly placeholder="Output will appear here..."></textarea>\n            </div>\n          </div>'
);

// Fix code-minifier
html = html.replace(
  '<div class="grid grid-cols-1 md:grid-cols-2 gap-4 h-[400px]">\n              <textarea id="cmInput" class="w-full p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl outline-none resize-none text-sm text-slate-800 dark:text-slate-200 font-mono shadow-sm" placeholder="Paste HTML, CSS, or JS code here..." spellcheck="false"></textarea>\n              <textarea id="cmOutput" class="w-full p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl outline-none resize-none text-sm text-slate-800 dark:text-slate-200 font-mono shadow-sm" readonly placeholder="Output will appear here..."></textarea>\n            </div>',
  '<div class="grid grid-cols-1 md:grid-cols-2 gap-4 min-h-[400px]">\n              <textarea id="cmInput" class="w-full p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl outline-none resize-y text-sm text-slate-800 dark:text-slate-200 font-mono shadow-sm" style="min-height: 400px; height: auto;" oninput="this.style.height=\'auto\'; this.style.height = this.scrollHeight + \'px\'; const out = document.getElementById(\'cmOutput\'); if(out) { out.style.height=\'auto\'; out.style.height = out.scrollHeight + \'px\'; }" placeholder="Paste HTML, CSS, or JS code here..." spellcheck="false"></textarea>\n              <textarea id="cmOutput" class="w-full p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700/60 rounded-xl outline-none resize-y text-sm text-slate-800 dark:text-slate-200 font-mono shadow-sm" style="min-height: 400px; height: auto;" readonly placeholder="Output will appear here..."></textarea>\n            </div>'
);

fs.writeFileSync(file, html);
